Squashed commit of the following:
commit c9e4e0927d94a52ce5e1699fcedaf32d86e9f1d5
Author: Hyoo Lim <hyoolim@gmail.com>
Date:   Tue Aug 26 09:53:41 2014 -0400

    Fixes compile error in maven.AnalyzeAllThread from Solr upgrade.

commit 9b7f9cc482678a8147c05e00641f7bbaa3b675e3
Author: Hyoo Lim <hyoolim@gmail.com>
Date:   Mon Aug 25 17:17:03 2014 -0400

    Fixes NoClassDefFoundError when running the projects caused by mismatched httpcomponents versions.

commit b4fa096751a908ec000e97323ef7d56a735bc8bb
Author: Hyoo Lim <hyoolim@gmail.com>
Date:   Mon Aug 25 17:14:15 2014 -0400

    Reverting unnecessary changes.

commit d176de49557cb4bf577b4aec47706d4da7d1bb84
Merge: d2fa1ff c4b557a
Author: Hyoo Lim <hyoolim@gmail.com>
Date:   Mon Aug 25 16:48:06 2014 -0400

    Merge branch 'master' into feature/solr-upgrade

commit d2fa1fffc3e283cb35019fedf3309306101c7a8c
Author: kelly <kelly@perfectsensedigital.com>
Date:   Mon Jun 30 14:57:33 2014 -0400

    update the code to use solr 4.8.1
    plus all dependent code changes

commit df0205a8ea45168c5e6c56f03e8fa6e7895ce664
Author: kelly <kelly@perfectsensedigital.com>
Date:   Mon Jun 30 14:56:26 2014 -0400

    add new config files

commit f467e0c729538351c84ae9dd19f25afb7fbfc496
Author: kelly <kelly@perfectsensedigital.com>
Date:   Mon Jun 30 14:56:19 2014 -0400

    move the old config files